### ISSUE TITLE
Core dump issue

### ISSUE THREAD

**Issue by adbeggs** [fritzsedlazeck/Spectre#1]
Hi

Tried to run spectre.py inside the conda environement.. get a Immediate coredump:

```
(/rds/projects/b/beggsa-clinicalnanopore/software/condaenvs/spectre) [beggsa@bb-pg-login02]$ ~/beggsa-clinicalnanopore/software/Spectre/spectre.py -h
Illegal instruction (core dumped)
```

**Comment by tuannguyen8390** [comment]
Very interesting, I did not have the same error my end @adbeggs. 

Did you try 

```python spectre.py``` instead

![image](https://github.com/fritzsedlazeck/Spectre/assets/47171822/560a2d9c-a48d-4043-aa8a-98c295884fd7)

If you fancy, I have a docker image handy @ `tuannguyen90/spectre:1.0`. More than happy to share the recipe btw

Cheers,

Tuan

**Comment by fritzsedlazeck** [comment]
Thank you both! This is quite a new tool so every feedback is helpful. @lfpaulin and @philippesanio will check these things out. 
Thanks
Fritz

**Comment by adbeggs** [comment]
Nope.. still broken... running it in a Redhat based HPC environment though... I'll try and pull your docker image as a singularity image now @tuannguyen8390

**Comment by adbeggs** [comment]
pysam appears to have a dependency on libbz2 - which I have loaded into our HPC and causes the coredump

**Comment by tuannguyen8390** [comment]
@adbeggs good to know it works your end. With our HPC instead of conda I opted for installation with pip, done much faster compare to make a conda env.

**Comment by philippesanio** [comment]
Hello, @adbeggs and @tuannguyen8390, my apologies for the delayed response, I am currently slammed with my thesis until next week on Tuesday.

@adbeggs Did you resolve this issue by loading libbz2 as an OS package or via Pip or Conda?

Cheers
~Philippe
