### ISSUE TITLE
CNLOH determination fails

### ISSUE THREAD

**Issue by adbeggs** [fritzsedlazeck/Spectre#13]
Another one.. really sorry:

Just seems to bug out at this point without generating anything... works fine without the --snv option

```
Spectre input: CNVCaller --coverage mosdepth/D23-51677.regions.bed.gz --sample-id D23-51677 --output-dir spectre2/ --reference /rds/homes/b/beggsa/beggsa-clinicalnanopore/genomes/grch38/genome.fa --blacklist grch38_blacklist_spectre.bed --min-cnv-len 1000 --snv clair/merge_output.vcf.gz
spectre::2024-03-22 10:01:46,588::INFO::spectre.spectre>  Spectre version: 0.2.0
spectre::2024-03-22 10:01:46,588::INFO::spectre.spectre>  Starting spectre
spectre::2024-03-22 10:01:46,588::INFO::spectre.spectre>  Evaluate if a new .mdr file needs to be created
spectre::2024-03-22 10:01:46,588::INFO::spectre.spectre>  Looking for default metadata.mdr in output directory
spectre::2024-03-22 10:01:46,588::INFO::spectre.spectre>  Using existing metadata file 
spectre::2024-03-22 10:01:46,613::INFO::spectre.spectreCNV>  Spectre calculating for: mosdepth/D23-51677.regions.bed.gz
spectre::2024-03-22 10:01:46,613::INFO::spectre.spectreCNV>  Analysing CN neutral state from SNV data
```

**Comment by oxygen311** [comment]
@philippesanio
I've fixed this bug already in dev branch and couple of others bugs as well, current bug is in line is this one:
https://github.com/fritzsedlazeck/Spectre/blob/17b65b7ccf7d8481169649a538781cb4a611c807/spectre/analysis/snv_analysis.py#L74

**Comment by adbeggs** [comment]
Actually no, when I run it in debug mode it finishes pretty quickly and the log file is empty. Command is:

```
spectre CNVCaller --coverage mosdepth/D23_26167.regions.bed.gz --sample-id D23_26167 --output-dir spectre2/ --reference 
~/beggsa-clinicalnanopore/genomes/grch38/genome.fa --blacklist ~/beggsa-clinicalnanopore/genomes/grch38/grch38_blacklist_spectre.bed --min-cnv-len 1000 --metadata ~/beggsa-clinicalnanopore/genomes/grch38/grch38spectremetadata.mdr --snv clair/merge_output.vcf.gz --dev
```

Reading the bugs above I wonder whether it might have something to do with AD/DP tags as I am using Clair3 which does not always output these in a standard way.

**Comment by adbeggs** [comment]
PS VCF is:

`-rwx------ 1 beggsa nobody 62M Aug 17  2023 clair/merge_output.vcf.gz`

**Comment by philippesanio** [comment]
> Reading the bugs above I wonder whether it might have something to do with AD/DP tags as I am using Clair3 which does not always output these in a standard way.

It should not matter since we are using the DP or AF/VAF from the VCF.

> PS VCF is:

From the file size it should compute fairly quickly.

I have pushed some changes (eb78bfe) which should address this bug #13 and the ones #10 #11 #12 to the main branch. However, they have not been packaged and are not available in the pip package yet. 
Could you be so kind and test Spectre directly from source by cloning it and let me know if that has resolved the issues you encountered?

In order to run Spectre this way you will have to add a file in the same directory where the README.md file is located with the following content:
```python
import sys
import re
from spectre.spectre import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
