### ISSUE TITLE
Empty result creates vcf instead of vcf.gz

### ISSUE THREAD

**Issue by bartcharbon** [fritzsedlazeck/Spectre#26]
When running Spectre on data that does not result in any CNV's the tool creates a vcf file rather than a vcf.gz file.
This makes it harder to use the tool in a pipeline.

Furthermore the vcf file contains one extra empty line which is a problem for using the vcf file in other tools.

**Comment by philippesanio** [comment]
Hi @bartcharbon,

Thanks for bringing up that issue. I have pushed a fix [07e61de](https://github.com/fritzsedlazeck/Spectre/commit/07e61dec60b1eb7d133edbf62b24766ad2269696)  that should solve the problem. 

The changes are currently only available in the repository. However, you can install Spectre manually by cloning the Spectre repository and installing it locally using pip:
```bash
pip install build
git clone https://github.com/fritzsedlazeck/Spectre.git
cd ./Spectre
python3 -m build
pip install dist/spectre_cnv-<VERSION>.tar.gz # replace <VERSION> with e.g. 0.2.0

If you encounter any further issues, please let me know!
Best, 
Philippe
