### ISSUE TITLE
Output Bed file description

### ISSUE THREAD

**Issue by reshu23** [fritzsedlazeck/Spectre#37]
Dear Team,

Spectre produces bed file as an output. I used spectre for one sample. Output bed file contains 6 columns. What is 6th column? What is the interpretation, when value in 6th column is 0.0?

**Comment by philippesanio** [comment]
Hi  @reshu23 

The 6th column of the BED file is the median coverage of the CNV. 
If it is 0.0 it would be DEL with a copy number of 0 (CN0), indicating a complete miss of information in that region.

Best,
Philippe

**Comment by reshu23** [comment]
Thank you.
