### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Tintest** [fritzsedlazeck/Spectre#41]
Hello,

I have used Spectre on 16 samples sequenced with PromethION flowcells and I get the following error when analyzing 5 samples out of 16. The 5 samples in question are all female, the other 11 are male. Should I change my ```--ploidy-chr``` parameter?

Error example : 
```shell
spectre::2024-12-03 12:40:50,909::INFO::spectre.spectre>  Spectre input: CNVCaller --coverage SampleA/SampleA.regions.bed.gz --sample-id SampleA.spectre --output-dir . --reference /srv/scratch/user/SV_nextflow/REF//GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta --blacklist /srv/scratch/user/SV_nextflow/REF//grch38_blacklist_spectre.bed --ploidy-chr chr1:2,chr2:2,chr3:2,chr4:2,chr5:2,chr6:2,chr7:2,chr8:2,chr9:2,chr10:2,chr11:2,chr12:2,chr13:2,chr14:2,chr15:2,chr16:2,chr17:2,chr18:2,chr19:2,chr20:2,chr21:2,chr22:2,chrX:2,chrY:0 --snfj SampleA.sniffles.snf.gz --min-cnv-len 80000 --snv SampleA.phased.VAF_fixed.vcf.gz --metadata /srv/scratch/user/SV_nextflow/REF//grch38_spectre_metadata.mdr --threads 14
spectre::2024-12-03 12:40:50,910::INFO::spectre.spectre>  Spectre version: 0.2.1
spectre::2024-12-03 12:40:50,910::INFO::spectre.spectre>  Starting spectre
spectre::2024-12-03 12:40:50,910::INFO::spectre.spectre>  Evaluate if a new .mdr file needs to be created
spectre::2024-12-03 12:40:50,910::INFO::spectre.spectre>  Using existing metadata file /srv/scratch/user/SV_nextflow/REF//grch38_spectre_metadata.mdr
Traceback (most recent call last):
  File "/usr/local/bin/spectre", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/spectre/spectre.py", line 642, in main
    spectre_run.spectre_exe()
  File "/usr/local/lib/python3.10/site-packages/spectre/spectre.py", line 292, in spectre_exe
    new_ploidy = (1 / (int(ploidy) / self.spectre_args.ploidy)) * self.spectre_args.ploidy
ZeroDivisionError: float division by zero
```

Thanks for your help.

**Comment by philippesanio** [comment]
Hi @Tintest,

Yes, I would recommend changing your --ploidy-chr flag. 

For your specific case of chrY:
The easy fix is to omit using chrY:0 with `--ploidy-chr` if you don't want to use chrY-> By default, the **blacklist will mask all of chrY** and thus disregards it.

Additional infos:
- `--ploidy-chr` is used to overwrite a specific chromosome ploidy state. Hence, you would not need to specify the ploidy state for each chromosome e.g. chr1, chr2, etc. as `--ploidy` (default=2) will set the ploidy state globally for all other chromosomes. We use it in human samples to only the ploidy state for chrX.
- If you only want specific chromosomes to be analyzed please use `--only-chr chr1,chr2,...`

Best,
Philippe

**Comment by Tintest** [comment]
Thank you for your prompt reply. 

If I have understood correctly, you still recommend using ```--ploidy-chr chrX:2``` for female samples and ```--ploidy-chr chrX:1``` for male samples and that's it ?

Regards.

**Comment by philippesanio** [comment]
> If I have understood correctly, you still recommend using --ploidy-chr chrX:2 for female samples and --ploidy-chr chrX:1 for male samples and that's it ?

Exactly!

Also, you might want to update to the latest GitHub version, as it introduced some changes and addressed some bugs. 
We are also currently working on getting the next major version ready for release very soon.

Best,
Philippe

**Comment by Tintest** [comment]
All right, I'll do that. Thank you so much.
