### ISSUE TITLE
CNV caller min_cnv_len

### ISSUE THREAD

**Issue by VICTO160** [fritzsedlazeck/Spectre#8]
When `spectre.py CNVcaller --help` is used the minimum CNV length option is listed as "min_cnv_len" but should be changed to "min-cnv-len".

**Comment by philippesanio** [comment]
Hi @VICTO160, thank you for letting us know!
We are going to change that in the next version, on which we are currently working, and planing of releasing it very soon.

Cheers,
Philippe
